# Generated by Django 5.0.1 on 2024-01-31 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_tasklist_use_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='use_id',
            new_name='user_id',
        ),
    ]
